//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPrj
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbProjectMusicStoreEntities : DbContext
    {
        public dbProjectMusicStoreEntities()
            : base("name=dbProjectMusicStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tAlbum> tAlbums { get; set; }
        public virtual DbSet<tAlbumType> tAlbumTypes { get; set; }
        public virtual DbSet<tMember> tMembers { get; set; }
        public virtual DbSet<tProductKind> tProductKinds { get; set; }
        public virtual DbSet<tProduct> tProducts { get; set; }
        public virtual DbSet<tPurchaseItem> tPurchaseItems { get; set; }
        public virtual DbSet<tShoppingCart> tShoppingCarts { get; set; }
        public virtual DbSet<tPlayList> tPlayLists { get; set; }
    }
}
